### ISSUE TITLE
Masternode/Payment UX/user friendliness

### ISSUE THREAD

**Issue by oriz456** [DiviProject/Divi-Desktop-Public#103]
-So regarding the masternode insufficient funds issue, I understand it is calculated dynamically and cannot be predicted ahead of time. However, when it throws the "insufficient funds" error after someone hits the deploy button, it doesn't tell them why. Some people, not realizing it's the fee, thinking they have the right collateral, are confused by it. It would just be easier if instead of simply saying "insufficient funds" it could say something like "insufficient funds(not enough funds for fee)".
*Done*

-I really don't see a need for both a "dismantle" and a "unsubscribe" button. we have had people only dismantle then come in months later to complain they keep getting charged, etc it's confusing. I recommend having only one button, called "dismantle or unsubscribe". within that button, all 3 options will be present(dismantle, unsubscribe, and both). Something like the following(ignore my design skills or lack thereof)

![image](https://user-images.githubusercontent.com/32154971/64481768-56f7ae80-d1b1-11e9-82ac-1970155ccd44.png)

*Having a single button with a single popup could lead to incorrect statuses and wordings within popup as subscriptions are managed in a tricky manner. if that is still required popup and button wordings need to be created for all possible statuses: paid and subscription active, not paid but subscription still active, prepaid for n-months, etc. Please create a separate task for this if still required as the scope is quite big.*

-no paypal payment info showing on testnet masternodes in the masternode box. Also should change from "payment cancels" to "payment expires".
*Done*

-Per previous discussions there was consensus to change the "manually started" to "masternode started" and the "masternode successfully started" to "mocci started". Right now manually started is very confusing.
*manually started has been changed. "masternode successfully started" comes from vps data that we don't controll*

-unsubscribe modal hangs like this once you unsubscribe via your paypal account:
![image](https://user-images.githubusercontent.com/32154971/66703539-b6ca0380-ece1-11e9-8d5f-64e4a7b555f7.png)

It still removes it, but you have to hit cancel because it never finishes on its own. Also, after you unsubscribe you still don't receive the option to subscribe again. I really think it's important to have the $ button back and give someone the option to re-subscribe.
*While the user has a subscription there is no need to pay twice as after cancelling subscription there might still be paid days. As if the subscription has been started 01.01 and cancelled 02.01 it still has 30 paid days. We have a monitoring job that checks subscrptions every day and $ button will be available after subscription is fully expired.*

**Comment by Divicoin** [comment]
➤ Eugene Ilagin commented:

Nick Saponaro please see our comments inline

**Comment by oriz456** [comment]
It doesn't make sense to show the $ after it is expired. I have had to help multiple people redeploy only because they didn't get to make the payment on time. if you use the $ button to pay, say, while you still have 10 days left, can't it just take the payment and not charge you again till the next ORIGINAL date?(meaning 40 days from now)

Also, still no payment info showing in testnet masternode box

**Comment by oriz456** [comment]
The unsubscribing modal still hangs.

Also, still no payment info showing in testnet masternode box

**Comment by oriz456** [comment]
Also, any time you try to deploy it keeps asking to log back into paypal even when one touch is checked. it doesn't do this via a regular browser but only since the in-wallet popup has been implemented.

**Comment by Divicoin** [comment]
➤ Eugene Ilagin commented:

regarding $ could someone please formalize all cases that we have in payment and deployment process at the moment as changing logic to what is asked to be done breaks the other payment areas like monitoring of inactive subscriptions.

regarding one touch login. it actually works but this feature has expiration (we don't controll time span). if you try to sign in, close the app, open again and try to pay - it will log you safely in.
