### ISSUE TITLE
Additional buttons in settings

### ISSUE THREAD

**Issue by oriz456** [DiviProject/Divi-Desktop-Public#104]
In settings we should add mnsync reset button, and resync button. Also add an “Export” button backup of wallet.dat for those who want to use it instead of backing manually.

**Comment by Divicoin** [comment]
➤ Eugene Ilagin commented:

Nick Saponaro will you please provide a command for mnsync reset? The rest will be implemented

**Comment by oriz456** [comment]
It's simply mnsync reset(divi-cli, of course)

**Comment by Divicoin** [comment]
➤ Eugene Ilagin commented:

Nick Saponaro could you please suggest a name for "mnsync reset" on the frontend?

**Comment by dkostenevich** [comment]
done (v1.4.17)
