### ISSUE TITLE
Notifications spamming whenever client reopened

### ISSUE THREAD

**Issue by oriz456** [DiviProject/Divi-Desktop-Public#107]
-When client is closed for a while then re-opened, every single transaction receives a notification. Only transactions received while client is open should create a notification, and not catch up on every transaction ever.

**Comment by dkostenevich** [comment]
@oriz456 please provide: app version & platform

**Comment by oriz456** [comment]
windows 10, version 1.4.12

**Comment by dkostenevich** [comment]
@oriz456 fixed (v1.4.16)
