### ISSUE TITLE
Change of password allows entering wrong password

### ISSUE THREAD

**Issue by oriz456** [DiviProject/Divi-Desktop-Public#109]
When going to change password from settings, it will let you enter a wrong password, and then let you enter a new password, and confirm the new password, only to then say wallet pass phrase is wrong. You should have to either fully unlock in order to be able to change a password, or, let you know that it is the wrong password once you enter it, not at the end of the process.

**Comment by dkostenevich** [comment]
@oriz456 fixed (v1.4.17)
