### ISSUE TITLE
Inconsistent behavior when deploying masternodes on 1.5.1

### ISSUE THREAD

**Issue by oriz456** [DiviProject/Divi-Desktop-Public#120]
All masternodes were deployed on testnet.

1. When deploying, the masternode does not show up on the list. However, there is an entry in masternode.conf. transaction shows as "moved", not "allocated".

2. When attempting to restart daemon, masternode tab now shows "...loading...please wait..." and stays on that no matter how long passes even when fully synced.

3. Only a full restart of the client as a whole(maybe the difference between restart of daemon and restart of client is cache?) fixes this issue, and now transaction shows as "allocated", other incoming transactions that never showed before are now confirming, and masternode is in the list.

4. Despite already having two active tokens that were not attached to any live masternodes, full payment was required for all new deployments. See pic attached. Note: I have 3 newly deployed masternodes and two that were dismantled, hence the 5 active tokens. All 3 newly deployed today required new tokens despite the other 2 already existing. No alias is attached to the other 2.

![image](https://user-images.githubusercontent.com/32154971/68174144-026f7600-ff4b-11e9-8c2c-9dc6d2148582.png)

**Comment by dkostenevich** [comment]
@oriz456 please check v1.5.2.

**Comment by oriz456** [comment]
All good now on the first 3, but the old subscriptions still don't work.
