### ISSUE TITLE
Advanced coin control enhancements and remaining issues

### ISSUE THREAD

**Issue by oriz456** [DiviProject/Divi-Desktop-Public#121]
-In advanced coin control("unspent" in history) user should be able to "select all" but also have the option to deselect the transactions they don't want to combine. for example, if I only want to combine 456 but not any other transactions, I could do that by selecting all, then sorting by amount, and deselecting any other transactions(like if someone sent me any funds).

-Another option should be to sort by date. But the date was wrong and showed the time you were looking at it instead of the time they were received. So I see that there is now no time at all showing. It is very important to be able to combine only newer funds vs older funds, etc, so we still need to show date/time, but show them right.

**Comment by dkostenevich** [comment]
done v1.5.2

**Comment by oriz456** [comment]
Both good now
