### ISSUE TITLE
Users are missing Cancel or Delete in Payment and Subscriptions

### ISSUE THREAD

**Issue by 7h3v01c3** [DiviProject/Divi-Desktop-Public#124]
![image](https://user-images.githubusercontent.com/16604693/68922296-13c93700-0730-11ea-8e8e-56024e01bb66.png)

This is for version 1.5.5

**Comment by dkostenevich** [comment]
@7h3v01c3 Please check previous requirements https://github.com/DiviProject/Divi-Desktop-Public/issues/100
https://prnt.sc/pxb4ud
