### ISSUE TITLE
Masternode Status & Verbiage update

### ISSUE THREAD

**Issue by 7h3v01c3** [DiviProject/Divi-Desktop-Public#131]
Ok UPDATE on Masternode Status
_______________________________
Ok, we can alleviate user concern and remove the need to use MNSYNC for the masternode status update by using the associated DIVI  APIs for masternode status.
Use a redundant check (2 out of 3 response)
Check all three of these APIs:
api.divscan.io/masternode/address
https://api.diviproject.org/v1/masternodes/address
https://divi.cr/dc/listmasternodes/address
When fetching the data from the APIs and you have a 2 of 3 or consensus.
For responses that return
EXPIRED
POSE_BAN
REMOVED
WATCHDOG_EXPIRED
or an empty array,
In console (masternode tab) display "Not Running, Contact Support"
For responses that return
PRE_ENABLED
ENABLED
in console display "Running "
For responses that return
UNKNOWN
In console display, alternating text fades "Loading" & "May take up to 15 minutes"
If the user clicks tab and the wallet hasn't finished calling the APIs,
in console display, alternating text fades "Loading" & "May take up to 15 minutes"
The wallet can cache the last known status and update this status calling the of APIs every 15 Minutes or upon wallet restarts, masternodes starts or deployments

**Comment by dkostenevich** [comment]
done (v1.5.16)
