### ISSUE TITLE
createRawTransaction description

### ISSUE THREAD

**Issue by 0o10** [DiviProject/Divi-Desktop-Public#133]
Just a note to update, btc is still used in the createRawTransaction description.
v.1.6.3
osx

![](https://storage.www.wrike.com/filemeta/thumb100/F140006724.A2811331)

┆Attachments: <a href="https://storage.www.wrike.com/attachments/140006724?accountId=2811331">73127084-cd3e5700-3f80-11ea-8b3a-cb156006cd1a.png</a>

**Comment by ilagin** [comment]
This description is return by daemon. Can't be changed on Desktop App side

**Comment by Divicoin** [comment]
➤ The Voice commented:

maybe a minor change in the 
https://github.com/DiviProject/Divi/blob/3728ad61b1044c68b282146efd3901e433e5b81f/divi/src/rpcwallet.cpp#L828

on next release

**Comment by Divicoin** [comment]
➤ The Voice commented:

There are actually a few I will note them

https://github.com/DiviProject/Divi/blob/3728ad61b1044c68b282146efd3901e433e5b81f/divi/src/rpcwallet.cpp#L336
https://github.com/DiviProject/Divi/blob/3728ad61b1044c68b282146efd3901e433e5b81f/divi/src/rpcwallet.cpp#L377

**Comment by Divicoin** [comment]
➤ German Luna commented:

I hunted down a few already. A few dozen or so. I'll be opening a PR, EOD today

**Comment by Divicoin** [comment]
➤ German Luna commented:

Should say that the PR is Open and ready for review.

**Comment by Divicoin** [comment]
➤ The Voice commented:

Thank you Ill update and close this when done

**Comment by 7h3v01c3** [comment]
Corrected for release in next version.
