### ISSUE TITLE
Telegram/discord link in the wallet

### ISSUE THREAD

**Issue by Divicoin** [DiviProject/Divi-Desktop-Public#146]
Telegram/discord link in the wallet

**Comment by Divicoin** [comment]
➤ Dmitry Kostenevich commented:

Abigail Loaiza Rojas
Please provide: 
1) direct links for Telegram & discord
2) place where they should be added (e.g. settings -> general (at bottom))

**Comment by Divicoin** [comment]
➤ Abigail Loaiza Rojas commented:

Discord: https://discord.gg/zdTvBWS
Telegram: https://t.me/diviproject

**Comment by Divicoin** [comment]
➤ The Voice commented:

Elias the Telegram link needs to point to support
https://web.telegram.org/divisupport

Allowing the user to use the computer they are on to communicating

**Comment by Divicoin** [comment]
➤ The Voice commented:

Abigail Loaiza Rojas I just updated the link 😀

**Comment by 7h3v01c3** [comment]
These need to be both linked to the Telegram Support Channel and the Discord support channel ID in server
