### ISSUE TITLE
Add "help and support"

### ISSUE THREAD

**Issue by Divicoin** [DiviProject/Divi-Desktop-Public#164]
add “help and support” which can take you to the wiki faq, to telegram support, etc. Right now help takes you to the website and exists only in the icon, would be cool to have in wallet too, but take to wiki...and have a separate website link. Also link to whitepaper from within wallet. We can also show the TG/Discord icons in there if we had a help and support tab

**Comment by 7h3v01c3** [comment]
These have been included since 1.6 and updated in 1.7 and 1.9.2.
