### ISSUE TITLE
Which Ports are used by Divi Desktop

### ISSUE THREAD

**Issue by Bubbu17** [DiviProject/Divi-Desktop-Public#212]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue
Which Ports are used by Divi Desktop
..

# More information

- Operating system and version:
id like to create a Linux Ubuntu Container containing a divi desktop! Therfore I need to Know the Ports to be forwarded ito the container.

Thanks for help in advance

ps. even better the link to a Docker Image if already existing

**Comment by 7h3v01c3** [comment]
51472 probably best for the entire range in 514##

The above includes testnet also.
