### ISSUE TITLE
Publish sources for android mobile appid=`io.divipay.divi`

### ISSUE THREAD

**Issue by emanuelb** [DiviProject/Divi-Desktop-Public#214]
I am looking for the source-code of `io.divipay.divi` app on google-play
https://play.google.com/store/apps/details?id=io.divipay.divi

This repo contain sources for the Desktop app while I am looking for sources of the android app, please publish them in this org on github.

**Comment by 7h3v01c3** [comment]
Sorry, wrong repo and the one you ask for is not open.


Best wishes to you though.
