### ISSUE TITLE
Mac Divi Desktop stuck on Connecting to daemon... with warning sign in bottom left corner.

### ISSUE THREAD

**Issue by XavierElon** [DiviProject/Divi-Desktop-Public#224]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue
When I open desktop divi on Ventura 13.0 OS Mac the screen gets stuck on connecting. to deamon... with a warning sign in the bottom left corner. Closing and restarting my computer did not fix the bug.
..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. .. Open on Mac
2. ..
<img width="1191" alt="Screenshot 2022-08-02 at 9 28 30 AM" src="https://user-images.githubusercontent.com/22874429/182386491-11e07189-4e31-44fe-b92d-334248987f1d.png">

# More information

- Operating system and version: Ventura 13.0 Mac OS Macbook Pro M1X
- Client version: 1.9.2

**Comment by SaschaHeyer** [comment]
Same issue with 
Mac OS version 12.5.1

Primer also failing
<img width="323" alt="Screenshot 2022-10-04 at 21 52 42" src="https://user-images.githubusercontent.com/1991664/193912906-6535c807-aebc-42c9-8b4f-cef6a73b8f04.png">

**Comment by Beasta** [comment]
same

**Comment by 7h3v01c3** [comment]
Support for this isn't here it is securely at https://support.diviproject.org or https://discord.com/channels/384135103959531520/674282389287075840
