### ISSUE TITLE
OSX 1.3.7 - No USD values & 0 balances on send - error

### ISSUE THREAD

**Issue by gingfinger** [DiviProject/Divi-Desktop-Public#61]
On OSX builds on 1.3.7 there is a display issue when trying to send . It is not pulling the USD values in the main overview, or on the send screen. When a user goes to confirm the send, then theres a 0 amount shown as the send amount.

**Comment by 99darwin** [comment]
Fixed in the upcoming version.

**Comment by 7h3v01c3** [comment]
Update also intermittent display issues on Windows
