### ISSUE TITLE
UX issues

### ISSUE THREAD

**Issue by oriz456** [DiviProject/Divi-Desktop-Public#62]
-So having the masternode sorting options is great, but it provides a by tier option as well as a reserved balance option which is essentially the same thing. I think Tier makes sense, but instead of “reserved balance” we can have it be by “name”(alphabetically).
***DONE***

-in transaction history “sort by category” does the same thing as sort by amount.
***DONE***

-The masternode boxes don’t make it clear that you can click them(cursor doesn’t change, no hand or anything), and clicking anywhere in the box(including the lightning bolt) expands them.
***DONE***

-the coinmarketcap and coingecko thing is a step in the right direction but should have the option to choose specific exchanges too I think(btw, they’re wrongly called exchanges in settings which theyre not). Also, by default I think it should show the average, and not both of them as that makes the top of the screen too heavy. I think I know which task this was and so I’ll quote from the original suggestion:

In the wallet, add option to choose what data you want the price to come from. I.E. which exchange, cmc, etc. If I choose to send $100 and it converts it to divi, it needs to be as accurate as possible. Using cmc api isn’t very accurate, but the best solution is imo leaving it to the discretion of the user and letting them pick whose price they want to use. Can also add like a ticker(that the user can turn off) that runs across and shows divi value in different crypto and traditional currencies in real time from the app.

Imo only a price from one source should be shown at a time. That should be the price displayed, but also the price the send will be based on, and should be based on the user’s choosing(say, bitrue price).
***DONE***

-As has already been mentioned, this staking on/off switch is totally bizarre, isn’t an actual switch, and shouldn’t come in place of a proper indicator. Instead we should have a real switch where you can turn staking on or off, and ALSO an indicator that tells you what is actually wrong but in a user friendly way. For example, if mintable = false it should say coins maturing. If everything but staking status is true it should say restart client. If wallet unlocked is false it should say unlock wallet. if enoughfunds is false it should say not enough funds.
***DONE***

-as bmt pointed out, “uninstall divi” shouldn’t say from “that computer” but "this computer".
***DONE***

-sort by date when entering a range does not sort by the entered range. I entered up to the 30th and it only showed up to the 22nd even though there were transactions after that.
***DONE***

-change password button lookin kinda funny

![bf4223737b6e1d7357ab8ec0f3738a0dc6f47cdb](https://user-images.githubusercontent.com/32154971/64086906-c4669380-cd08-11e9-8dbc-8fa593834cde.png)
***DONE***

-masternodes tab in settings still needs tool tips
***DONE***

-items per page setting doesn’t work right the first time, if you set it to 50 it will show that but will still only have 25 transactions on that page, when you go to the next one it will show correctly and then when you go back to the first it will show correctly. the problem is magnified, however, if for example you have a total of 190 transactions and chose the 250 setting. in that case, since they’re all supposed to be on one page, it will only show 25, and won’t let you move to the next page, so you’re kinda stuck not seeing most of your transactions.
***DONE***

-checking or unchecking “display addresses in transaction list” makes no difference to how they’re displayed.
***DONE***

-notifications for receiving rewards work but why does it look like it’s a “zzz” icon? lol

![fe8b7c4ab3142bf97a3b858292b0d2086eda13ba](https://user-images.githubusercontent.com/32154971/64087023-33dc8300-cd09-11e9-858c-4b3151e99d63.png)
***DONE***

-Are there supposed to be any sounds when receiving notifications? because there aren’t any.
***DONE***

-Also when receiving notifications, even masternode rewards just say “stake reward”.
***DONE***

-Also, receiving no notifications for send/receive.
***DONE***

**Comment by oriz456** [comment]
It appears some of those have been fixed in .11. 

I do wanna point out the few that have not and/or there has not been feedback telling me they won't/can't/shouldn't:

-items per page on first attempt still show the wrong number of items.

-the exchange prices - is there a plan to add any of those as well or just aggregators…and once again I think default should be average.

-masternode box - clicking the lightning bolt still expands whole box.

-Staking switch is better, but if mnsync is false should probably say syncing. Right now it says restart client which should only be used if everything is true but staking status is false. Also, due to the fact enoughcoins = true even when there are 0 coins, maybe there is a way to make sure there is at least 1 coin in the wallet before it says “coins maturing”. We should also probably find a way to communicate it’s a staking switch, as right now a newb wouldn’t really know what it’s for.

**Comment by dkostenevich** [comment]
@oriz456 
* items per page on first attempt still show the wrong number of items.
will be fixed
* the exchange prices - is there a plan to add any of those as well or just aggregators…and once again I think default should be average.
average by default now, you can verify it:
remove `settings` from local storage or fresh install
* masternode box - clicking the lightning bolt still expands whole box.
will be fixed

**Comment by Divicoin** [comment]
➤ Eugene Ilagin commented:

Nick Saponaro our answers are inline in *** ***. Please take a look

**Comment by oriz456** [comment]
All looks good to me. Just need to find exchange api's.
