### ISSUE TITLE
UX #3

### ISSUE THREAD

**Issue by oriz456** [DiviProject/Divi-Desktop-Public#68]
-Still the dreaded “delete”. lets please change it to “dismantle”. lets also add a “dismantle and subscribe” option in there.

![63b317a81f410b50bed2403786ba5248e87355d2](https://user-images.githubusercontent.com/32154971/64088043-9899dc80-cd0d-11e9-95e6-f2a584deda29.png)
***DONE***

-This should say “hide app” or “close app” instead of closing app.

![4c9d70a6957495954c5abf6983c55309e1878906](https://user-images.githubusercontent.com/32154971/64088136-12ca6100-cd0e-11e9-9f30-177e96981708.png)
***DONE***

-What’s up with the key fragments thing? not exactly a user friendly description.

![32d9d3511ed9fbcfecd232c266033670b6fc31f0](https://user-images.githubusercontent.com/32154971/64088148-1f4eb980-cd0e-11e9-9b5a-e39bf4315371.png)
***Please provide a description that should be placed***

-Combine UTXOs should get a tooltip as well, also, there's a typo
***DONE***

-UTXO = UTXOs. Missing the S
***DONE***

![a87b2435061200e964c5a50f55acad4a191db63e](https://user-images.githubusercontent.com/32154971/64088287-b87dd000-cd0e-11e9-8a3d-ee2201fc24e3.png)

-Still says token

![5751a53de3e3ca349205203413a3d254405fc6c3](https://user-images.githubusercontent.com/32154971/64088293-c16ea180-cd0e-11e9-8732-2cce621bdd72.png)
***DONE***

Both parts should say passcode.

-This is really weird wording:

![292b1a70683eeb3fcc3a997d9ba6afe58914682f!UNITO-UNDERSCORE!2!UNITO-UNDERSCORE!690x356](https://user-images.githubusercontent.com/32154971/64088339-f67af400-cd0e-11e9-9013-e57c7bb17dbd.png)

For one it’s not only google authenticator. and the last bit is just bad grammer. something like “please enter either your 2FA passcode or your manual entry code” would be better I think.
***DONE***

-when daemon is restarting(say after dismantling one masternode) other masternodes show as not started. This can startle some people…maybe we can have it just show “connecting” or “retrieving data”(again) instead…
***Not done at the moment. Requires a separate task and time***

-while one of the insufficient funds upon deployment has been fixed (when you dismantle and redeploy), another has not. Sometimes the issue is people actually not having a large enough fee to simply pay for the allocation. From suggestion a while back:

"Wallet should be able to tell which issue it is and let them know the root cause. if he root cause is NOT the fee(but instead whatever bug/error it is that the zapwallet/restart seems to fix), maybe if insufficient funds && spendable >= funds required for that tier, a prompt can come up prompting them to refresh the wallet.<—[again this part is pretty much null and void if we implement the restart before deployment or other solutions]

Maybe it can even be automated where it automatically realizes the issues, provides the user with feedback, and refreshes the wallet, and in settings along with the other suggestions that could be automated in this thread we can have a button that asks the user when certain actions need to be taken, if they want to be prompted or dealt with it automatically(kinda like anti viruses have those settings). If user chooses automatically, then the refresh, as well as the other suggestions(start masternode, etc) will be done automatically. If user chooses to receive prompts, then a friendly prompt will walk them through exactly what needs to be done, and will either direct them to where to do it from in settings, or have a button within that prompt that they can click to perform said action).

We can’t just have grandma look up telegram and go ask in support. things need to be MUCH friendlier and explained to them when they happen from within the wallet as to what exactly is going on."

If only the fee is not enough, I suggest instead of just “insufficient funds” for it to actually tell them why.
***Not done. The fee is being calculated dynamically. We already had such issue during mobile development.***

-Allow choosing how you want the fee to be taken out. You should be able to set a default setting in settings but also change it on the fly via the send screen, and be able to choose for it to either add it to the amount you wish to send, like it does now, or have it be a part of it.
***Not done. The fee is being calculated dynamically. We already had such issue during mobile development.***

-Something I just found out is you can actually start a masternode even if you’re only unlocked for staking(by start I mean the lightning bolt).
***DONE***

**Comment by Divicoin** [comment]
➤ Eugene Ilagin commented:

Nick Saponaro  our answers are inline in *** ***. Please take a look

**Comment by oriz456** [comment]
So regarding the masternode insufficient funds issue, I understand it is calculated dynamically and cannot be predicted ahead of time. What I'm referring to though, is when it throws the "insufficient funds" error after someone hits the deploy button, it doesn't tell them why. Some people, not realizing it's the fee, thinking they have the right collateral, are confused by it. It would just be easier if instead of simply saying "insufficient funds" it could say something like "insufficient funds(not enough funds for fee)".
