### ISSUE TITLE
Primer issues

### ISSUE THREAD

**Issue by oriz456** [DiviProject/Divi-Desktop-Public#69]
-primer did not work for me after seed restore and got stuck on “starting daemon” many times.

-Primer also doesn’t work properly after recovery. I tried the first time and everything finished ok except for daemon wouldn’t start(hung on #9). So no biggie, restarted client myself and everything worked. But the next time I did it I got the “something isn’t quite right” error and the third time I did it it got stuck at #9 again only this time closing the app didn’t work without a hard shutdown, it froze. And after a hard shutdown everything was corrupted. I don’t know if it’s due to the recovery or just generally we’re still having so many issues with primer, but it definitely was not smooth or painless. It failed time after time until I just did a reindex via cli. Definitely should at the very least until issues are sorted have the option to close primer modal at that point of the process, so you can restart daemon on your own through settings, instead of having to do a hard shutdown for the whole client.

-Primer name should likely be changed and should not ask people to "restore"(this keeps confusing people).

For more primer input see UX issues.

**Comment by oriz456** [comment]
I have figured out many times using "clear cache" prior to using the primer resolves SOME of those issues. In case that helps with reproducing or fixing the issue.

**Comment by oriz456** [comment]
It seems like the major issue right now is hanging at the restart daemon step. I suggest adding an "x" so you can close the modal and restart on your own without having to close the whole client when this happens, also, right now it tries for quite a while then goes to another screen with "retry" or "abort" and retry doesn't actually even attempt to do anything. In the screen itself, while it's still trying to restart daemon after a few minutes it should prompt to retry or add a manual restart daemon button to the modal.

**Comment by oriz456** [comment]
#111 has been closed but all issues above are still ongoing, tested and not confirmed fixed.

**Comment by 99darwin** [comment]
@oriz456 from what I can see this issue is now in testing. Check beta version 1.4.17 for fixes.

**Comment by Divicoin** [comment]
➤ Nick Saponaro commented:

Eugene Ilagin sounds like Clear Cache is working but Primer is not when the local data is corrupt. Is it possible that we're skipping a step when running the Primer that Clear Cache does not skip?

**Comment by Divicoin** [comment]
➤ Eugene Ilagin commented:

Hi Nick Saponaro we weren't able to reproduce any of the issues discussed. Please make sure that the latst version is being used. Besides that the Clear Cache removes the same set of folders as Primer does. And according to the new app logic a "stuck daemon" pop-up should appear in case the daemon fails to start after Primer restore. If you have more details regarding the issue (logs, screens) this will help us a lot.

**Comment by oriz456** [comment]
A screenshot won't really do much other than show it hanging on #9 and then popping up the "something isn't quite right" modal, but I will try again later today and then assuming it fails again I'll send a debug log. Bear in mind after using "Clear Cache" button daemon restarts without an issue(but syncs the "old fashioned" way) and only fails to start after using primer.

**Comment by oriz456** [comment]
I have forwarded debug to nick. 

Also, I think one of the issues(not necessarily causing mine but can't be good either way) is that daemon is on throughout the whole process and then it restarts it at the end. It would probably be better, if after stopping daemon on step #1, it just didn't start it again until after the extraction, instead of starting and stopping multiple times.

**Comment by Divicoin** [comment]
➤ Eugene Ilagin commented:

we have slightly changed the daemon start/stop logic so this should potentially fix the issue. however daemon is supposed to never run during the entire primer download and restore process

**Comment by oriz456** [comment]
Seems like progress with primer, but now, it completes it(doesn't error out) but once it is done it is only 83% synced and still has to sync the rest p2p. Any ideas?

**Comment by Divicoin** [comment]
➤ Eugene Ilagin commented:

It turned out that the remote job that creates primer has been accidentally killed. We have reeenabled it and will keep an eye on it.

**Comment by oriz456** [comment]
So I just tried testing it again and still only gets me around ~469k blocks

**Comment by Divicoin** [comment]
➤ Eugene Ilagin commented:

Can you please try again? should be fine now

**Comment by oriz456** [comment]
Just tested, and it now ends up on block 100 at the end of restore

**Comment by oriz456** [comment]
We seem to be back to the daemon issue from above. That seemed to have gotten fixed when the snapshot was not right, but now daemon won't start at all again when using primer.

Additionally, some download speeds are slower and if a certain amount of time passes without the file downloaded, it also errors out even though nothing is technically wrong except for a slow connection. is it possible to only have the "something's not quite right" popup be active after a certain time of not being successful only AFTER the file is downloaded? and to just wait it out while it's trying to download.

**Comment by dkostenevich** [comment]
@oriz456 did you tried on v1.5.2?

**Comment by oriz456** [comment]
Yes, I had issues initially but after letting it sit for a while it started(even after it already errored out), then when I tried again it worked the next time. I'll keep trying a few more times
