### ISSUE TITLE
New Install on 1.4.0 sticks on splash screen

### ISSUE THREAD

**Issue by 7h3v01c3** [DiviProject/Divi-Desktop-Public#85]
Sticks on splash screen on a new installation. Does not change until you open a second instance of Divi Desktop

..

Create a new user in windows, install directly from browser download.

It starts here 
![image](https://user-images.githubusercontent.com/16604693/65080138-77fc9400-d955-11e9-9949-54a5f43a30f3.png)

then the Windows defender firewall pops up and  you give access
![image](https://user-images.githubusercontent.com/16604693/65080262-bc882f80-d955-11e9-8916-42a0c8933da0.png)

but it returns to 
![image](https://user-images.githubusercontent.com/16604693/65080138-77fc9400-d955-11e9-9949-54a5f43a30f3.png)

and doesnt change unless you open a second instance of Divi Desktop.

It is running I confirmed running GitBash
![image](https://user-images.githubusercontent.com/16604693/65080345-ed686480-d955-11e9-9024-290c81be5c16.png)

@Giff_1 said it happens on OSX intermittently

This was originally reported by Rapid Retro @achilleze confirmed by myself with new windows user and install.

- Win 10 and OSX Mojave
- Client version: 1.4.0

**Comment by Divicoin** [comment]
➤ Eugene Ilagin commented:

Doesn't seem to appear on newer versions

**Comment by dkostenevich** [comment]
@oriz456 fixed (v1.4.12)
