### ISSUE TITLE
Modal to restart daemon when stuck

### ISSUE THREAD

**Issue by oriz456** [DiviProject/Divi-Desktop-Public#86]
Can we have a popup notification after, say 5 minutes, if daemon doesn't restart(any time it has to - whether after sync, during mocci, or other times). The popup should have a button to retry starting daemon, if it still won’t start it should forward them to the forum and/or telegram support, so that they can be guided through how to configure their AV correctly or figure out whatever the issue causing the block is. At times, even on my own machine, I will need to navigate to settings and hit restart daemon. But, a if other users experience such issues it would be more user friendly to let them do it from a modal that pops up automatically.

**Comment by dkostenevich** [comment]
@oriz456 done (v1.4.16)

**Comment by oriz456** [comment]
So the original issue also mentioned adding an option from within the modal to be directed to our support for further troubleshooting...can we add that in? @dkostenevich @99darwin
