### ISSUE TITLE
UX - maybe a different message once a spend is confirmed

### ISSUE THREAD

**Issue by 7h3v01c3** [DiviProject/Divi-Desktop-Public#90]
![image](https://user-images.githubusercontent.com/16604693/65279280-b4a9c600-dae2-11e9-8796-29c9e4c621bb.png)

right now it says on the senders' history "These funds are now spendable"

Maybe it should say "These funds are confirmed as sent"

**Comment by oriz456** [comment]
Agreed, also in #70

**Comment by dkostenevich** [comment]
@oriz456 fixed (v1.4.16)
