### ISSUE TITLE
In divi-desktop app can access cmd window when staking without password

### ISSUE THREAD

**Issue by retrocoderz** [DiviProject/Divi-Desktop-Public#96]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue

In divi-desktop app can access cmd window when staking without entering a password. 

Was talking with TheVoice on telegramand he suggested I file here (this is Rapid Retro; aka achilleze)

..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. Start divi-desktop app, and start staking by entering your password
2. Then click on the "Cmd window"
3. Password request comes up. Don't enter the password instead click X to close the window. 
4. Cmd window will still open and you can run all the normal commands. I didn't try testing send/receive but if you can do that this would be a bit of a security hole. 

# More information

- Operating system and version: Dedicated core i3, ubuntu Latest, x86-64b, 
- Client version: Latest divi-desktop wallet: 1.4.5

**Comment by oriz456** [comment]
Agreed, and it happens in more screens than that, see comment in issue #66

**Comment by dkostenevich** [comment]
fixed in v1.4.11
