### ISSUE TITLE
Advanced coin control issues

### ISSUE THREAD

**Issue by oriz456** [DiviProject/Divi-Desktop-Public#97]
-If you don't choose ANY utxo and then hit combine, you get this screen

![image](https://user-images.githubusercontent.com/32154971/66250820-d4153580-e715-11e9-99a2-fc77b1f53574.png)

Basically same as combining everything from settings. you then click combine and get this

![image](https://user-images.githubusercontent.com/32154971/66250822-ebecb980-e715-11e9-9fd4-b1a4569a9405.png)

Originally, there were many utxos on that screen and now none. They were confirming.

![image](https://user-images.githubusercontent.com/32154971/66250834-0c1c7880-e716-11e9-9742-bd6e0cca7bf6.png)

Notice the time.

![image](https://user-images.githubusercontent.com/32154971/66250844-438b2500-e716-11e9-9c17-84fc50ad2586.png)

Also notice it created several new combined ones(in fact, 8). not 0 and not 1 either. Why 8?

But in the unspent screen, it doesn't show the time they were created. it actually shows **current time** as in, the time you're viewing that screen.

![image](https://user-images.githubusercontent.com/32154971/66250883-b1cfe780-e716-11e9-8f2a-5a487ddd02a2.png)

Also, when you only combine just, say 2...it says "2 were combined". that's weird. it should say "2 transactions were combined"

![image](https://user-images.githubusercontent.com/32154971/66250895-ce6c1f80-e716-11e9-864e-ef95708d98b1.png)

Last but not least, it seems to be waiting for 15 confirmations. Why? shouldn't it be 6?

![image](https://user-images.githubusercontent.com/32154971/66250916-1428e800-e717-11e9-81f8-2ece0c6648dc.png)

**Comment by dkostenevich** [comment]
@oriz456 fixed (v1.4.12)

**Comment by oriz456** [comment]
So I see that there is now no time at all in the unspent tab. why can't it just show the same time it shows in "receive" as far as when it came in?
