### ISSUE TITLE
I get this a lot with the address book .. in addition every deleted one is always with the Toast message "undefined"

### ISSUE THREAD

**Issue by abifabulista** [DiviProject/Divi-Desktop-Public#98]
I get this a lot with the address book .. in addition every deleted one is always with the Toast message "undefined"
![](https://storage.www.wrike.com/filemeta/thumb100/F140005521.A2811331)

┆Attachments: <a href="https://storage.www.wrike.com/attachments/140005521?accountId=2811331">66425136-2ed7b700-e9cc-11e9-9d05-d8e551d87105.png</a>

**Comment by dkostenevich** [comment]
fixed
